### ISSUE TITLE
MySQL/MariaDB configuration change - possibly move temporary area onto same filesystem as data files

### ISSUE THREAD

**Issue by genghisken** [lsst-uk/lasair-lsst#10]
The temporary table files are being written into /tmp which is an extremely small partition. While it's great that it doesn't create potential problems for the database partition itself that temporary files are written there, the WHOLE SERVER is threatened by filling up /tmp which is on the root partition.

This is (at least) the 4th time this has happened. I propose:

The mysqltmp (or whatever the config file setting is) area is moved from /tmp to EITHER its own partition (hard) or the /var/lib/mysql partition (easy).  The disadvantage of the latter is that accidentally filling up /var/lib/mysql could corrupt database files. On the other hand it may be possible to limit the size of the mysqltmp area from within the config settings.

**Comment by genghisken** [comment]
Own partition would be the ideal setup - different from the root partition and the data partition. My worry with putting it on the data partition is the potential for filling it up and corrupting the database. No-one cares if a temporary partition gets corrupted!

**Comment by genghisken** [comment]
I think this might need to wait until the Heat / Terraform activity is done.

**Comment by gpfrancis** [comment]
@genghisken The latest deployment playbook (see deploy/database.yaml) gives the database instances a separate partition for /tmp (size configurable in settings.yaml).

Is this sufficient to address the issue?

**Comment by genghisken** [comment]
Moving /tmp to its own partition *should* protect the OS if /tmp/ fills up, but not completely, since the OS will occasionally write stuff to /tmp. But I think this is mitigated enough to close this issue.

The ultimate solution I think is to change the my.cnf to:
* Limit the temporary table size on disk (already manually deployed on the galera nodes as `tmp_disk_table_size=10G`)
* Change the location of the temporary tablespace(s) e.g. to /mysqltmp.
Since raising this issue I became aware that my.cnf templates are under Ansible control for standalone MariaDB config, but NOT under Ansible control for the Cluster Control deployment of Galera nodes.  In order to do a complete fix, we would need to deploy Cluster Control with Ansible, then alter the Cluster Control templates with Ansible, then finish the Cluster Control deployment of Galera.
