### ISSUE TITLE
Make fake Sherlock

### ISSUE THREAD

**Issue by gpfrancis** [lsst-uk/lasair-lsst#118]
Make a fake version of Sherlock that returns random (but deterministic) classifications.

**Comment by RoyWilliams** [comment]
- Each classification AGN, BS, CV, NT, ORPHAN, SN, VS should be assigned at random with probability 1/7
- There will be no UNCLEAR
- If the classification is SN or NT, there should also be a `distance` and/or`z` and/or `photoz` in the sherlock packet each with probability 1/2, or else zero.
- Distance (Mpc) should be chosen as `math.exp(random.uniform(2.5,7))`, which gives a range 12 to 1100, biased to the smaller values
- The z and photoz can each be computed as `0.00023 * math.exp(random.uniform(2.5,7))`
- Example: classification=SN, distance = exp(3) = 20.08 Mpc, z = 0.00023*exp(6) = 0.093, photoz = 0

**Comment by RoyWilliams** [comment]
The RA and Dec of the alert can be randomised at the same stage by the fake Sherlock. These sprinkle the alerts over the whole sphere
```
RA   = random.uniform(0.0, 359.999)
Dec = math.asin(random.uniform(-1, 1)) * 180/math.pi
```

**Comment by gpfrancis** [comment]
Merged into develop.
