### ISSUE TITLE
Possible Sherlock Inconsistency/Bug 

### ISSUE THREAD

**Issue by thespacedoctor** [lsst-uk/lasair-lsst#12]
The is one for @gpfrancis I think! The original bug report is coming from a user and results are needed for a paper.

Have a look at this object: <https://lasair-ztf.lsst.ac.uk/objects/ZTF21aadkgpm/>

The Sherlock classification displayed on the webpage and returned from the Lasair `objects` API resource is as follows:

> The transient is synonymous with _[SDSS J111459.66+272712.1](http://skyserver.sdss.org/dr12/en/tools/explore/Summary.aspx?id=1237667324324479076)_; an r=18.44 mag galaxy found in the SDSS catalogue. It's located 0.7" from the galaxy core.

However, if I run Sherlock from the `lasair-ztf-sherlock-1` node with a command like this:

```bash
sherlock -N match -- 168.748762 27.453335 /opt/lasair/sherlock_settings.yaml
```

I consistently get the result:

> The transient is possibly associated with <em><a href="http://skyserver.sdss.org/dr12/en/tools/explore/Summary.aspx?id=1237667324324479075">SDSS J111500.8+272659.9</a></em>; a J=13.96 mag galaxy found in the SDSS/2MASS/PS1 catalogues. It's located 12.25" N, 14.95" W (23.2 Kpc) from the galaxy centre. A host z=0.062 implies a <em>m - M =</em> 37.23.

I get this same result when running all 40 individual detection coordinates (from individual alert packets) and for the object's mean RA and Dec. The same result is also returned from the `sherlock_position` API resource.

So the question is, why does the classification on the webpage not reflect what I am getting offline?

- Is Sherlock-lite returning different results from Sherlock?
- Is the a low-precision issue in the RA and Dec given to Sherlock at any point?

**Comment by gpfrancis** [comment]
I agree that all current instances of sherlock appear to be giving the same result for that position ([SDSS J111500.8+272659.9](http://skyserver.sdss.org/dr12/en/tools/explore/Summary.aspx?id=1237667324324479075)) - I've also tested one of the running containers.

However, the last alert for that object appears to be from over two years ago so we should be comparing what's in the object database against what would have been produced by the then current version of Sherlock (2.1.7) using whatever survey database we were using at that point. Do you have old versions available to test?

**Comment by thespacedoctor** [comment]
Ah of course that's the issue! Thanks Gareth!

**Comment by gpfrancis** [comment]
The Sherlock wrapper includes the version of Sherlock used in the alert packet. Maybe it would be good to have that made available somewhere rather than my having to infer it from the date. I recall we did discuss versioning and provenance issues when we were first hashing out the specification for annotations and other people were against it, although I can't recall why.
