### ISSUE TITLE
Document sherlock stop/start

### ISSUE THREAD

**Issue by RoyWilliams** [lsst-uk/lasair-lsst#125]
Please document the LSST version of stopping and starting sherlock [in the PoO](https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/2763161628/Lasair+Principles+of+Operation)

**Comment by gpfrancis** [comment]
Updated for ingest, sherlock and filter. Existing versions marked as ZTF only, new versions marked as LSST only.
