### ISSUE TITLE
Topic name length

### ISSUE THREAD

**Issue by RoyWilliams** [lsst-uk/lasair-lsst#132]
- Currently topic names for annotators are limited to 32 characters (see [here](https://github.com/lsst-uk/lasair-lsst/blob/main/webserver/lasair/apps/annotator/models.py#L8))
- Kafka allows topic names up to 255 characters

**Comment by gpfrancis** [comment]
And [here](https://github.com/lsst-uk/lasair-lsst/blob/main/common/schema/lasair_sql/annotations.sql) it is limited to 16. We should either set the type to `bigstring` and enforce a limit of 80 chars or set the type to `text` and the limit to 255.
