### ISSUE TITLE
Organise slack alert channels 

### ISSUE THREAD

**Issue by gpfrancis** [lsst-uk/lasair-lsst#138]
Slack alerts from different deployments (dev, ztf-prod, lsst-prod, etc.) should go to different channels so that we can distinguish important alerts.

**Comment by tms-epcc** [comment]
For further information on the background to this task, see [Lasair SE Incident log entry for 09/MAR/24](https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/3446833169/09+MAR+24+Failed+to+notice+ingest+stop+due+to+lack+of+alerts)
