### ISSUE TITLE
Make filters work

### ISSUE THREAD

**Issue by RoyWilliams** [lsst-uk/lasair-lsst#16]
When trying to make a new filter, there is a syntax error.
![Screenshot 2023-05-10 at 15 16 12](https://github.com/lsst-uk/lasair-lsst/assets/8886481/76d25a3d-12c9-46c8-bf79-57df3700a8ae)

**Comment by thespacedoctor** [comment]
See fix in https://github.com/lsst-uk/lasair-lsst/pull/4

The LSST dev webserver is running this branch if you want to test before merging @RoyWilliams
