### ISSUE TITLE
Make a RESET script for the ingest

### ISSUE THREAD

**Issue by RoyWilliams** [lsst-uk/lasair-lsst#161]
- Make a script with the `stop.sh` and `start.sh` called `reset.sh`
- It makes it so the same alerts are ingested again when the `start.sh ingest` is run
- Perhaps reset the kafka or change the default `group_id` in `common/settings.py`

**Comment by gpfrancis** [comment]
Documented how to use the standard Kafka tools to do this: https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/3627778050/Kafka+Offsets
