### ISSUE TITLE
Annotators sending data wider than column width trigger a 500 internal server error

### ISSUE THREAD

**Issue by genghisken** [lsst-uk/lasair-lsst#173]
Annotators can send data to Lasair and trigger a 500 error if a value is wider than the column width. E.g. NEEDLE managed to cause this error when it sent a `version` value wider than 16 characters (column is `varchar(16)`). We should consider at least truncating the value to fit into the column or raise an exception if the data is too wide.

Problem was raised in lasair4 (ZTF) but I suspect we will only fix in lasair-lsst, which is fair enough.

For the record, the code that triggered the problem is below:
```python
 L.annotate(
            topic_out, 
            objectId, 
            classification,
            version='xs-db3-needle-v1-mixed-r', 
            explanation=explanation, 
            classdict=classdict, 
            url='')
        print(objectId, '-- annotated!')
        log.write('object %s -- annotated!\n' % objectId)
        return 1
```

**Comment by gpfrancis** [comment]
I suggest that the API should validate its input and return a 400 error with an appropriate message on failure.
