### ISSUE TITLE
Add alerting on host level errors

### ISSUE THREAD

**Issue by gpfrancis** [lsst-uk/lasair-lsst#2]
e.g. full disk should send alarm to Slack/email - from Grafana?

**Comment by tms-epcc** [comment]
11/JAN/24
Further information regarding monitoring and alerts as collected from the discussion at the [Lasair SE process meeting on 16/NOV/23](https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/3306815490/Lasair+SE+process+meeting+-+16+NOV+23)
- Whilst have grafana dashboards, these are not always being looked at.
- A Slack message though can be set up to indicate when a metric in Grafana is breached
- There are potentially 55 such metrics. There are two possible options for dealing with all these.
- Could use Ansible to configure Grafana and hence the scripts can be stored in GitHub if there will be lots of alerts for these metrics.
- Requires more discussion but probably in first instance will send an alert Slack message based on whether or not web server is up.

**Comment by gpfrancis** [comment]
Alert on website down is done. Can add more alerts as and when required.
