### ISSUE TITLE
Whacky error when changing the name of a filter query

### ISSUE THREAD

**Issue by mFulton07** [lsst-uk/lasair-lsst#23]
I received this weird error when changing the name of my pre-existing filter query. Changes were saved successfully, but will my filter no longer run on the Kafka stream?

![Screenshot 2023-06-08 at 11 51 21](https://github.com/lsst-uk/lasair-lsst/assets/58076215/ceb3cf34-182b-42c3-aa00-5e352abe033c)

Named changed from "Fastfinder Alertstream" to "Fastfinder Feeder Query". Link to filter query in question: https://lasair-ztf.lsst.ac.uk/filters/97/.

**Comment by RoyWilliams** [comment]
Its perfectly normal. When you modify a filter, Lasair deletes all the records from the old query, both file cache and kafka topic. But the user wants to test the kafka output from the new filter, so we insert 10 records from the new filter. When you put those into kafka it just says its making a new topic for these.
