### ISSUE TITLE
DEBUG=true causes Django failure

### ISSUE THREAD

**Issue by gpfrancis** [lsst-uk/lasair-lsst#29]
Trying to install a web server from scratch with the setting DEBUG=True results in something like the following error:
```
File \"/home/ubuntu/lasair-lsst/webserver/users/models.py\", line 11, in <module>
    class Profile(models.Model):
File \"/home/ubuntu/lasair-lsst/webserver/users/models.py\", line 21, in Profile
    with open(staticRoot + '/img/default.jpg', mode='rb') as readFile:
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/lasair-lsst/webserver/staticfiles/build/img/default.jpg'
```

Setting DEBUG=false appears to fix it.

**Comment by thespacedoctor** [comment]
When `DEBUG=True`, django sets the `staticRoot` path to wherever you store/stage your assets *before* running the collect static method with django. This staged area is `/home/ubuntu/lasair-lsst/webserver/staticfiles/build/`, but this does not get created until a 'gulp build' is performed (see instructions in the README file in the staticfiles directory).

The cleanest, simplest way forward is to deploy with `DEBUG=False`. This way django will look in `/home/ubuntu//lasair-lsst/webserver/static` for all web-assets. This directory is version controlled and ships with the code.

**Comment by gpfrancis** [comment]
Thanks. Have changed the default to false.
