### ISSUE TITLE
pip for deployment

### ISSUE THREAD

**Issue by RoyWilliams** [lsst-uk/lasair-lsst#30]
Both the lasair_service and the ingest nodes should have the following installed
pip3 install confluent_kafka
pip3 install fastavro
pip3 install python-snappy
pip3 install cassandra-driver
pip3 install gkdbutils
pip3 install ephem

**Comment by gpfrancis** [comment]
The current lists of packages to install.

Ingest:
- confluent-kafka
- fastavro
- cassandra-driver
- gkutils
- gkdbutils
- docopt
- gkhtm 

Service:
- gkhtm
- gkutils
- docopt
- numpy
- mocpy
- requests
- mysql-connector-python
- fink-client
- lasair

Should the following be removed from ingest?
- gkutils
- docopt
- gkhtm 

Should all of the current packages be removed from service?
