### ISSUE TITLE
Make new lasair-cassandra for deployment

### ISSUE THREAD

**Issue by RoyWilliams** [lsst-uk/lasair-lsst#38]
The cassandra tables should be built from the lasair schema, not bolted into the gkservercollection.

The new ansible code will look like [lasair-deploy/main.yml](https://github.com/lsst-uk/lasair-lsst/blob/develop/deploy/roles/lasair_database/tasks/main.yml) and will run all the [CREATE TABLE](https://github.com/lsst-uk/lasair-lsst/tree/develop/common/schema/lasair_cql) scripts using the [cassandra module from galaxy](https://galaxy.ansible.com/community/cassandra)

**Comment by genghisken** [comment]
The initial cut of this will use the command shell rather than the Ansible galaxy command module, since it's not yet integrated into Ansible and only has one rating so far. I don't want to exchange one galaxy dependency for another!  (I'll take a look at it for future modifications.)
