### ISSUE TITLE
sherlock wrapper update

### ISSUE THREAD

**Issue by RoyWilliams** [lsst-uk/lasair-lsst#39]
The sherlock wrapper needs updating for the new syntax of the alerts. Specifically, [this code](https://github.com/lsst-uk/lasair-lsst/blob/develop/pipeline/sherlock/wrapper.py#L156-L167) should be replaced with:
```
    for alert in alerts:
        diaObject = alert.get('diaObject')
        name = diaObject.get('diaObjectId')
        if not name in annotations:
            if not name in names:
                names.append(name)
                ra.append(diaObject['ra'])
                dec.append(diaObject['decl'])
```
Note that in the LSST schema, it is the diaObject that has RA and Dec that goes into Sherlock, whereas with ZTF there was no object and we just used the latest candidate ( i.e. diaSource)

I would make this change myself, but I can't find it is on `lasair-lsst-dev-sherlock`

**Comment by RoyWilliams** [comment]
Hi Gareth
Thank you for setting up the new branch [1] so that the sherlock wrapper can handle LSST alerts, in response to issue 39 [2]. I have a couple of questions:

(1) How does this code get executed? I know it goes into a docker container, but where does that happen? I can't see any clone of the repo on lasair-lsst-sherlock? What is the command to make the container from the code, and how does that new container get into the pipeline?

(2) Have you tried running it yet? I am not seeing the "ztf_sherlock" that would be the result of processing the "ztf_ingest" topic. Can we do that ASAP as the milestone is due at the end of this week?

(3) I note that you assume the incoming alert contains either a diaObject or a ssObject, is there a reference for this? My reading of the document [3] is that ssObjects arrive in a separate stream the next day. I would suggest we remove this assumption and just panic if we get an alert woth no diaObject. Besides, we are not paid for solar system object processing and have had no communication from those who are.

I have copied this message into the github issue
Roy

[1] https://github.com/lsst-uk/lasair-lsst/blob/feature/sherlock_wrapper_update/pipeline/sherlock/wrapper.py#L157-L172
[2] https://github.com/lsst-uk/lasair-lsst/issues/39
[3] https://docushare.lsst.org/docushare/dsweb/Get/LDM-612 section 2.2.2

**Comment by gpfrancis** [comment]
The Dockerfile is in pipeline/sherlock/Dockerfile. The image needs to be rebuilt and the version in the playbook updated.

My reading of [LDM-612](https://ldm-612.lsst.io) section 2.2, in combination with the [DPD] (https://lse-163.lsst.io/), is that alerts could be either a new diaObject, an existing diaObject or an existing ssObject. The bit that happens later is the detection of *new* ssObjects and they don't go into the main alert stream.

**Comment by RoyWilliams** [comment]
OK, we can leave in the dichotomy of diaObject / ssObject. 
Yes I see the dockerfile in the github. But the repo isn't cloned on the VM. 
```
ubuntu@lasair-lsst-dev-sherlock:~$ ls -l
-rw-rw-r-- 1 ubuntu ubuntu 513 Jun 19 15:35 sherlock-wrapper-compose.yml

ubuntu@lasair-lsst-dev-sherlock:~$ ls -l /opt/lasair/
total 32
drwxr-xr-x 2 ubuntu www-data 4096 Jun 19 15:37 __pycache__
-rw-rw-r-- 1 ubuntu ubuntu   1310 Jun 19 15:35 config.yaml
-rw-r--r-- 1 ubuntu ubuntu   4546 Jun 19 15:37 main.py
-rw-rw-r-- 1 ubuntu ubuntu    136 Jun 19 15:37 sherlock_service.ini
-rw-rw-r-- 1 ubuntu ubuntu     95 Jun 19 15:35 sherlock_service_settings.yaml
-rw-rw-r-- 1 ubuntu ubuntu   1682 Jun 19 15:35 sherlock_settings.yaml
srw-rw---- 1 ubuntu www-data    0 Jun 19 15:37 sherlocksvc.sock
-rw-rw-r-- 1 ubuntu ubuntu    102 Jun 19 15:35 wrapper_runner.json

```

**Comment by RoyWilliams** [comment]
Can tell me precisely how a push to the repo gets executed on the sherlock node?
