### ISSUE TITLE
Cannot connect to LSST-dev webserver

### ISSUE THREAD

**Issue by RoyWilliams** [lsst-uk/lasair-lsst#40]
SSH tunnel and http://localhost:8080/
Works great

https://lasair-lsst-dev-web.lsst.ac.uk/
--  refused to connect.

https://lasair-lsst-dev.lsst.ac.uk/
-- DNS address could not be found.

**Comment by gpfrancis** [comment]
It works for me. Is this still an issue?

**Comment by RoyWilliams** [comment]
All fixed.
