### ISSUE TITLE
Retiring active queries

### ISSUE THREAD

**Issue by RoyWilliams** [lsst-uk/lasair-lsst#49]
I suggest that we should have a process that users' active filters be converted to inactive filters if not wanted. Otherwise they will keep building up over time. Note that the filter node needs to execute all active filters for every batch of incoming alerts.

We already have a `date_modified` attribute in each filter, so we can test if it is more than, say, a year, and if so, send the user an email telling them to save the filter again, thus resetting the `date_modified`. 

But if any filter is both active and has not been modified in 1.5 years, then it it demoted to be inactive.

**Comment by gpfrancis** [comment]
Discussion in https://github.com/lsst-uk/lasair4/issues/200
