### ISSUE TITLE
Review security scan

### ISSUE THREAD

**Issue by gpfrancis** [lsst-uk/lasair-lsst#54]
Email from Mark H:

> Lasair Team,
>
> I’ve just finished a security scan of all the publicly visible web services running on Somerville, and compiled reports on any instances showing possible vulnerabilities. In general, the Lasair instances are fine, but there are some minor level concerns with a few instances, and one instance which needs to be reviewed in more detail.
>
> Minor concerns: lasair-lsst-dev-svc.lsst.ac.uk, lasair-ztf-web.lsst.ac.uk, lasair-lsst-dev-web.lsst.ac.uk, lasair-dev-web.lsst.ac.uk, lasair-dev-svc.lsst.ac.uk, lasair-jenkins.lsst.ac.uk Take a look at the attached reports for these. The main common issues are the TLS header and the possible BREACH vulnerability.
> 
> Further review: lasair-lsst-dev-kafka_pub.lsst.ac.uk
Look over the scan results and let me know when you’d like to discuss either in person, on Teams, or on Slack. Basically there’s a lot of things in there that may or may not be an issue (like all th
e visible backup tar files), and others that look like genuine vulnerabilities which should be mitigated.
>
>Cheers,
>  Mark

[lasair-jenkins.report.txt](https://github.com/lsst-uk/lasair-lsst/files/12229740/lasair-jenkins.report.txt)
[lasair-lsst-dev.report.txt](https://github.com/lsst-uk/lasair-lsst/files/12229741/lasair-lsst-dev.report.txt)
[lasair-dev.report.txt](https://github.com/lsst-uk/lasair-lsst/files/12229742/lasair-dev.report.txt)
[lasair-dev-svc.report.txt](https://github.com/lsst-uk/lasair-lsst/files/12229743/lasair-dev-svc.report.txt)
[lasair-lsst-dev-kafka_pub.report.txt](https://github.com/lsst-uk/lasair-lsst/files/12229744/lasair-lsst-dev-kafka_pub.report.txt)

**Comment by RoyWilliams** [comment]
Thank you Gareth. There is overwhelming detail. Can you see any actual priorites?

**Comment by gpfrancis** [comment]
Yes, top priority is figuring out what's going on with security groups and why some of these ports are even reachable.

**Comment by GregBlow** [comment]
Looks to be issue with how security groups are applied in new version of Openstack. See: https://github.com/lsst-uk/somerville-operations/issues/112

**Comment by gpfrancis** [comment]
The security group issue appears to be with Somerville, not us: https://github.com/lsst-uk/somerville-operations/issues/112

This accounts for why ports 8082/8083 are visible on lasair-lsst-dev-kafka_pub when they should not be. If you take those ports away then there is nothing left on that instance to scan.

**Comment by gpfrancis** [comment]
The line "nginx/1.18.0 appears to be outdated" which appears in various places is just a comment because we are running an LTS release of ubuntu and does not represent a vulnerability.

**Comment by gpfrancis** [comment]
I'm not sure that setting the `X-Frame-Options` and `X-Content-Type-Options` headers is high priority, but it should be easy to do at the Nginx proxy.

**Comment by gpfrancis** [comment]
Setting the `Strict-Transport-Security` is probably something we should do on Jenkins and production servers, but not on dev.

**Comment by gpfrancis** [comment]
` /: The Content-Encoding header is set to "deflate" which may mean that the server is vulnerable to the BREACH attack. See: http://breachattack.com/`

Unable to reproduce.

**Comment by gpfrancis** [comment]
Issues with services on port 8080 are also a result of https://github.com/lsst-uk/somerville-operations/issues/112

**Comment by gpfrancis** [comment]
Summary:
- Issues with services on ports 8080, 8082 and 8083 are primarily due to problems with security groups on Somerville (should not normally be externally accessible)
- Regarding the potential BREACH vulnerability, I was unable to reproduce. More detail required if @astrodb thinks this is a real issue.
- There are some security related HTTP headers that we can look at setting at the proxy level. I think this is probably useful, but not high priority. Created a new issue to track: #55

**Comment by GregBlow** [comment]
The Somerville-wide issue is I believe resolved now.
