### ISSUE TITLE
lasair-lsst-dev DNS is broken

### ISSUE THREAD

**Issue by RoyWilliams** [lsst-uk/lasair-lsst#59]
Gareth -- welcome back, hope you had a nice holiday! I can't access our LSST test machine https://lasair-lsst-dev.lsst.ac.uk/, it says can't be reached. But the nginx and mod_wsgi seem to be running OK. Can you have a look? -- Roy

**Comment by gpfrancis** [comment]
The instance wasn't in any security groups except for default - it needed to be added to one to permit access.

**Comment by RoyWilliams** [comment]
Thanks Gareth!
