### ISSUE TITLE
speed up watch list crossmatching

### ISSUE THREAD

**Issue by thespacedoctor** [lsst-uk/lasair-lsst#6]
Just pinning this for the future. I think I/we can significantly increase the crossmatching speed.

**Comment by RoyWilliams** [comment]
There are two crossmatch algorithms, bulk and streaming. Which one do you think can be accelerated, and how?

(1) [Bulk code](https://github.com/lsst-uk/lasair4/blob/develop/common/src/run_crossmatch.py): Input is a set of cones (ra,dec,radius) and objects (ra,dec,HTM). For each cone it makes an HTM query clause then uses the database to select objects whose HTM matches.

(2) [Streaming code](https://github.com/lsst-uk/lasair4/blob/develop/pipeline/filter/check_alerts_watchlists.py): Input is an object (ra, dec) and a watchlist. The union of the cones has been converted to a MOC, then it uses the method `moc.contains()` to decide if the object is in the watchlist, and if so, finds which cone.

**Comment by thespacedoctor** [comment]
I have some code I wrote for Sherlock that could help. The trick might be in matching lists against one another instead of matching one source at a time. I would need to investigate to be sure but will wait until after UI release day.

**Comment by thespacedoctor** [comment]
I've added a new drop-in replacement script for `run_crossmatch.py` called `run_crossmatch_optimise.py`. It can be found on `lasair-ztf-web` at `~/lasair4/utility`.

Here are some comparison run times for matching a small(ish) and large watchlist against the full ZTF database.

`time python3 run_crossmatch.py 139`

vs

`time python3 run_crossmatch_optimsed.py 139`

| Watchlist ID  | Source Count | Results | Current Match Time  | Optimised Match Time | 
| :------------ | :----------- |:----------- |:----------- |:----------- | 
| 1175  (Milliquas)    | 1021800  | 127126 hits  | 55m37s | 1m49s | 
| 139 (E+A galaxies) | 51907 |  870 hits | 2m52s | 5s | 

So, it is roughly 30 times faster :)

If you're happy, I can prepare a pull request.

**Comment by RoyWilliams** [comment]
Dave -- this looks fabulous! But I worry about all the dependencies, the fundamentals, the Humpty, the use of a custom logging instead what the rest of Lasair uses. Can you point me to the code and documentation for conesearch:
```
from HMpTy.mysql import conesearch
```
Thanks!

**Comment by thespacedoctor** [comment]
Hi Roy, HMpTy and Fundamentals are my codes, so they are within our control. Here are the HMpTy docs:

https://hmpty.readthedocs.io/en/master/

You will see I am passing an empty (i.e. dummy) logger as Lasair does not use the standard Python logging much.

**Comment by RoyWilliams** [comment]
Dave
Your new code is an agenda item on tomorrow's meeting. Would be great if you can attend.
https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/3284926465/18+October+2023

In particular, can we have a new button on the watchlist page -- as illustrated in the agenda -- which causes run_crossmatch to be executed. Perhaps the button can only appear if the number of cones in the watchlist is less than say 100,000? That way we can moderate use of this expensive functionality if necessary.
Roy

**Comment by thespacedoctor** [comment]
Hi Roy,

Sure thing, I'll be there. We can discuss the button logic at the meeting :)
