### ISSUE TITLE
Document process for persistent topics

### ISSUE THREAD

**Issue by gpfrancis** [lsst-uk/lasair-lsst#60]
Add something to the POO documenting how to make a topic non-expiring.

**Comment by gpfrancis** [comment]
Draft documentation at https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/3262676993/Persistent+Topics+draft

**Comment by RoyWilliams** [comment]
This looks like just the thing. What we asked for and more! 
Where should the code run? 
Do I log in to the lasair-lsst-dev-kafka-0 node?
Has the code been written? 
Will you add it to one of our repos?

**Comment by gpfrancis** [comment]
See PR #63
