### ISSUE TITLE
Lasair DNS switch for Somerville outage 18th September 2023

### ISSUE THREAD

**Issue by GregBlow** [lsst-uk/lasair-lsst#62]
Tracking here. 

Modify DNS for lasair-ztf.lsst.ac.uk as per https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/3096772652/Lasair+Status+Page#Updating-DNS, then revert once maintenance is concluded.

This will likely be between 08:30-09:00 on the 18th of September.

Please assign this issue to me.

**Comment by markgbeckett** [comment]
@GregBlow Is there a Plan B if, for any reason, you are not able to action the ticket on morning of 18th?

**Comment by GregBlow** [comment]
If I am unable, @gpfrancis is also able and should be about.

**Comment by GregBlow** [comment]
pre-action testing has address https://lasair-ztf.lsst.ac.uk/ pointing here:

![image](https://github.com/lsst-uk/lasair-lsst/assets/2021333/a713c0bd-a0ae-47ec-8eb1-d511be64f7fb)

**Comment by GregBlow** [comment]
![image](https://github.com/lsst-uk/lasair-lsst/assets/2021333/01f30a82-3611-4eae-8a14-aa89649e437e)

**Comment by GregBlow** [comment]
![image](https://github.com/lsst-uk/lasair-lsst/assets/2021333/ac1eddf9-b2d2-405e-9ce1-2c1f485d0469)

**Comment by GregBlow** [comment]
![image](https://github.com/lsst-uk/lasair-lsst/assets/2021333/96c6ef08-f3e9-4de3-a560-560529ac8313)

**Comment by GregBlow** [comment]
change made, testing in a bit.

**Comment by GregBlow** [comment]
![image](https://github.com/lsst-uk/lasair-lsst/assets/2021333/a105d36a-9e3d-4006-a82c-e06e705f503b)

**Comment by RoyWilliams** [comment]
Thanks Greg -- looks like its redirected to RAL correctly. I'm happy that now we have two people (you and Gareth) who can do this. -- Roy

**Comment by GregBlow** [comment]
![Uploading image.png…]()

**Comment by GregBlow** [comment]
will keep issue open until reversion.

**Comment by GregBlow** [comment]
change reverted at request of @RoyWilliams . Network not officially returned to service but appears available with no indication it will be going away.
