### ISSUE TITLE
Auto ceph mounts on server reboot

### ISSUE THREAD

**Issue by genghisken** [lsst-uk/lasair-lsst#64]
Can we change the config for mounting ceph filesystems from:

```
noauto
```
to
```
nofail
```
This will allow servers to be rebooted without having to explicitly mount ceph filesystems after reboot. It will also still allow the server to boot if for some reason the ceph filesystem failed to boot (e.g. ceph unavailable).

**Comment by gpfrancis** [comment]
Done.
