### ISSUE TITLE
The cassandranodes entry is hard wired in gkansible.gkservercollection

### ISSUE THREAD

**Issue by genghisken** [lsst-uk/lasair-lsst#75]
We need to make the cassandranodes entry configurable since this is incompatible with creating a second cluster on the same network (e.g. for storing cutouts).

**Comment by RoyWilliams** [comment]
replace "cassandranodes" with play_hosts

**Comment by genghisken** [comment]
This is done on my latest gkansible/gkservercollection. Future installs should work OK, but it's hard to test without trashing and rebuilding a cassandra cluster.
