### ISSUE TITLE
Marshall testing

### ISSUE THREAD

**Issue by gpfrancis** [lsst-uk/lasair-lsst#79]
Mostly looks good to me, with the following relatively minor points:

- Pleased to report that Marshall notebook runs fine on Nublado (could maybe tweak the README a bit to cover this scenario though)
- Would it make sense to have an option to make the format of veto/fave files to be compatible with the watchlist format? (i.e. option to include ra and dec)
- Veto and fave should probably be radio button (i.e. not possible to select both).
- Notebook is sufficiently profligate with API queries that we run into rate limit very quickly - can we make it more efficient?
- Running into rate limit is not handled gracefully, just throws an exception
- Not sure random group ID is a good default (maybe leave all options commented out to start and force user to choose what they want?)

**Comment by RoyWilliams** [comment]
- Glad it runs OK!
- Radio button is a good idea -- will have to see what happens if its favourite then they change to veto!
- The batching of API calls I had thought of but was too lazy. Also will make it much faster. Lets see if I can work up some energy.

**Comment by RoyWilliams** [comment]
- The veto/fave files are not really watchlists, so don't want to do that.
- Veto/fave has radio-button behavior now.
- There is only one API call per run of the marshall -- all batched.
- No more random group ID
