### ISSUE TITLE
Intermittent fail of test for storing cutouts in Cassandra

### ISSUE THREAD

**Issue by genghisken** [lsst-uk/lasair-lsst#85]
Looks like cassandra sometimes times out when dropping tables or keyspaces

```
        cls.session.execute("DROP TABLE cutouts")
        cls.session.execute("DROP KEYSPACE %s" % keyspace)
```

Need to introduce an exception trap or timeout or other meta check to make sure the execute has completed succesffully.

**Comment by gpfrancis** [comment]
Increased the default timeout from 10s to 30s and the timeout on DROP KEYSPACE specifically to 300s. Decided against ignoring the error entirely as we probably do want to know about it if hangs indefinitely.
